name: Bug report
description: Report a bug or regression
labels: ["type:bug", "status:triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Clear, reproducible steps help a lot.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
  - type: input
    id: version
    attributes:
      label: Version / Commit
      placeholder: e.g., commit SHA or tag
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - mobile
        - server
        - infra
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      render: shell